---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: true

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-wheezy
  driver_config:
    box: debian-wheezy
    box_url: http://projects.tsuntsun.net/~nabeken/boxes/vagrant-debian-wheezy.box
  run_list:
  - recipe[apt]

suites:
- name: multi
  run_list:
    - recipe[openldap::multi]
    - recipe[openldap-test::mailaccount]
    - recipe[minitest-handler]
  encrypted_data_bag_secret_key_path: test/integration/secret_key
  attributes:
    openldap:
      slapd_rid: "0000"
      server_id: 100
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap-slave.example.com"
      slapd_master: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
      indexes:
      - "mailDomain,mailStatus eq"
      local_schemas:
      - "mailaccount.schema"
      local_schemas_cookbook: "openldap-test"
      peers:
      - "ip:127.0.0.1"
      - "ipv6:::1%FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF"
- name: slave
  run_list:
    - recipe[openldap::slave]
    - recipe[openldap-test::mailaccount]
    - recipe[minitest-handler]
  encrypted_data_bag_secret_key_path: test/integration/secret_key
  attributes:
    openldap:
      slapd_rid: "0000"
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap-slave.example.com"
      slapd_master: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
      indexes:
      - "mailDomain,mailStatus eq"
      local_schemas:
      - "mailaccount.schema"
      local_schemas_cookbook: "openldap-test"
      peers:
      - "ip:127.0.0.1"
      - "ipv6:::1%FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF"
- name: server
  run_list:
    - recipe[openldap::server]
    - recipe[openldap::auth]
    - recipe[minitest-handler]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
- name: unmanaged_ssl
  run_list:
    - recipe[openldap-test::ssl]
    - recipe[openldap::server]
    - recipe[openldap::auth]
    - recipe[minitest-handler]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      manage_ssl: false
      tls_checkpeer: true
      pam_password: sha
      ssl_dir: "/etc/ldap/ssl"
      ssl_cert: "/etc/ldap/ssl/ldap.example.com.pem"
      ssl_key: "/etc/ldap/ssl/ldap.example.com.pem"
      cafile: "/etc/ldap/ssl/ldap.example.com.pem"
- name: tls_disabled
  run_list:
  - recipe[openldap::server]
  - recipe[openldap::auth]
  - recipe[minitest-handler]
  attributes:
   openldap:
     server: localhost
     rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
     tls_enabled: false
     passwd_ou: peeps
     shadow_ou: ninjas
     group_ou: pirates
     automount_ou: barge
